"""Contenu anglais et espagnol, niveau debutant.

Meme reserve que pour le portugais : ce sont des paires de traduction et des
phrases d'usage, verifiees une a une. Ce n'est pas une progression concue par
un enseignant, et l'application ne doit jamais pretendre le contraire.
"""

PAQUETS = [
    {
        "id": "anglais-a1-bases",
        "nom": "Anglais A1 — Bases",
        "langue": "en",
        "description": "Saluer, se presenter, les mots de tous les jours.",
        "niveau": "A1",
        "cartes": [
            ("Hello", "Bonjour / Salut"),
            ("Good morning", "Bonjour (le matin)"),
            ("Good evening", "Bonsoir"),
            ("Goodbye", "Au revoir"),
            ("See you soon", "À bientôt"),
            ("How are you?", "Comment vas-tu ?"),
            ("I'm fine, thanks", "Je vais bien, merci"),
            ("Thank you", "Merci"),
            ("You're welcome", "De rien"),
            ("Please", "S'il te plaît"),
            ("Sorry", "Désolé"),
            ("Excuse me", "Excusez-moi"),
            ("Yes", "Oui"),
            ("No", "Non"),
            ("Maybe", "Peut-être"),
            ("What's your name?", "Comment t'appelles-tu ?"),
            ("My name is Paul", "Je m'appelle Paul"),
            ("Nice to meet you", "Enchanté"),
            ("I'm French", "Je suis français"),
            ("Where are you from?", "D'où viens-tu ?"),
            ("I don't understand", "Je ne comprends pas"),
            ("Can you repeat?", "Peux-tu répéter ?"),
            ("Do you speak French?", "Parles-tu français ?"),
            ("How do you say …?", "Comment dit-on … ?"),
            ("I speak a little English", "Je parle un peu anglais"),
            # Nombres
            ("one", "un"),
            ("two", "deux"),
            ("three", "trois"),
            ("four", "quatre"),
            ("five", "cinq"),
            ("six", "six"),
            ("seven", "sept"),
            ("eight", "huit"),
            ("nine", "neuf"),
            ("ten", "dix"),
            ("twenty", "vingt"),
            ("hundred", "cent"),
            ("thousand", "mille"),
            # Jours
            ("Monday", "lundi"),
            ("Tuesday", "mardi"),
            ("Wednesday", "mercredi"),
            ("Thursday", "jeudi"),
            ("Friday", "vendredi"),
            ("Saturday", "samedi"),
            ("Sunday", "dimanche"),
            ("today", "aujourd'hui"),
            ("tomorrow", "demain"),
            ("yesterday", "hier"),
            # Verbes
            ("to be", "être"),
            ("to have", "avoir"),
            ("to go", "aller"),
            ("to do / to make", "faire"),
            ("to want", "vouloir"),
            ("to can", "pouvoir"),
            ("to know", "savoir / connaître"),
            ("to speak", "parler"),
            ("to eat", "manger"),
            ("to drink", "boire"),
            ("to sleep", "dormir"),
            ("to see", "voir"),
            ("to hear", "entendre"),
            ("to like", "aimer bien"),
            ("to need", "avoir besoin de"),
            # Quotidien
            ("the house", "la maison"),
            ("the door", "la porte"),
            ("the water", "l'eau"),
            ("the bread", "le pain"),
            ("the food", "la nourriture"),
            ("the street", "la rue"),
            ("the city", "la ville"),
            ("the train", "le train"),
            ("the car", "la voiture"),
            ("the shop", "le magasin"),
            ("the money", "l'argent"),
            ("the work", "le travail"),
            ("the friend", "l'ami"),
            ("the family", "la famille"),
            ("How much is it?", "Combien ça coûte ?"),
            ("Where is …?", "Où est … ?"),
            ("On the left", "À gauche"),
            ("On the right", "À droite"),
            ("Straight ahead", "Tout droit"),
            ("What time is it?", "Quelle heure est-il ?"),
            ("I need help", "J'ai besoin d'aide"),
            ("It's open", "C'est ouvert"),
            ("It's closed", "C'est fermé"),
        ],
    },
    {
        "id": "espagnol-a1-bases",
        "nom": "Espagnol A1 — Bases",
        "langue": "es",
        "description": "Saluer, se presenter, les mots de tous les jours.",
        "niveau": "A1",
        "cartes": [
            ("Hola", "Bonjour / Salut"),
            ("Buenos días", "Bonjour (le matin)"),
            ("Buenas tardes", "Bonjour (l'après-midi)"),
            ("Buenas noches", "Bonsoir / Bonne nuit"),
            ("Adiós", "Au revoir"),
            ("Hasta luego", "À bientôt"),
            ("¿Qué tal?", "Ça va ?"),
            ("Muy bien, gracias", "Très bien, merci"),
            ("Gracias", "Merci"),
            ("De nada", "De rien"),
            ("Por favor", "S'il vous plaît"),
            ("Perdón", "Pardon"),
            ("Lo siento", "Je suis désolé"),
            ("Sí", "Oui"),
            ("No", "Non"),
            ("¿Cómo te llamas?", "Comment t'appelles-tu ?"),
            ("Me llamo Ana", "Je m'appelle Ana"),
            ("Mucho gusto", "Enchanté"),
            ("Soy francés", "Je suis français"),
            ("¿De dónde eres?", "D'où viens-tu ?"),
            ("No entiendo", "Je ne comprends pas"),
            ("¿Puedes repetir?", "Peux-tu répéter ?"),
            ("¿Hablas francés?", "Parles-tu français ?"),
            ("Hablo un poco de español", "Je parle un peu espagnol"),
            # Nombres
            ("uno", "un"),
            ("dos", "deux"),
            ("tres", "trois"),
            ("cuatro", "quatre"),
            ("cinco", "cinq"),
            ("seis", "six"),
            ("siete", "sept"),
            ("ocho", "huit"),
            ("nueve", "neuf"),
            ("diez", "dix"),
            ("veinte", "vingt"),
            ("cien", "cent"),
            ("mil", "mille"),
            # Jours
            ("lunes", "lundi"),
            ("martes", "mardi"),
            ("miércoles", "mercredi"),
            ("jueves", "jeudi"),
            ("viernes", "vendredi"),
            ("sábado", "samedi"),
            ("domingo", "dimanche"),
            ("hoy", "aujourd'hui"),
            ("mañana", "demain"),
            ("ayer", "hier"),
            # Verbes
            ("ser", "être (permanent)"),
            ("estar", "être (état, lieu)"),
            ("tener", "avoir"),
            ("ir", "aller"),
            ("hacer", "faire"),
            ("querer", "vouloir"),
            ("poder", "pouvoir"),
            ("saber", "savoir"),
            ("hablar", "parler"),
            ("comer", "manger"),
            ("beber", "boire"),
            ("dormir", "dormir"),
            ("ver", "voir"),
            ("vivir", "vivre"),
            # Quotidien
            ("la casa", "la maison"),
            ("la puerta", "la porte"),
            ("el agua", "l'eau"),
            ("el pan", "le pain"),
            ("la calle", "la rue"),
            ("la ciudad", "la ville"),
            ("el tren", "le train"),
            ("el coche", "la voiture (Espagne)"),
            ("la tienda", "le magasin"),
            ("el dinero", "l'argent"),
            ("el trabajo", "le travail"),
            ("el amigo", "l'ami"),
            ("la familia", "la famille"),
            ("¿Cuánto cuesta?", "Combien ça coûte ?"),
            ("¿Dónde está …?", "Où est … ?"),
            ("A la izquierda", "À gauche"),
            ("A la derecha", "À droite"),
            ("Todo recto", "Tout droit"),
            ("¿Qué hora es?", "Quelle heure est-il ?"),
            ("Necesito ayuda", "J'ai besoin d'aide"),
            ("Está abierto", "C'est ouvert"),
            ("Está cerrado", "C'est fermé"),
            # Le piege classique, comme en portugais
            ("Soy profesor", "Je suis professeur (métier, durable)"),
            ("Estoy cansado", "Je suis fatigué (état passager)"),
        ],
    },
]
