"""Contenu portugais (Portugal), niveaux A1 et A2.

Ce que je peux garantir, et ce que je ne peux pas
------------------------------------------------
Ce sont des **paires de traduction**, verifiees mot a mot, et des phrases
courtes d'usage courant. C'est un travail de vocabulaire, pas un cours : je
peux affirmer que « casa » veut dire « maison », je ne peux pas pretendre
avoir concu une progression pedagogique validee.

L'ordre des unites suit une logique d'usage — on salue avant de conjuguer —
et c'est un defaut raisonnable, pas une methode eprouvee. Un professeur de
portugais ferait mieux, et son paquet serait le bienvenu.

Variante : portugais europeen. Les differences avec le bresilien sont
signalees quand elles changent le mot lui-meme.
"""

PAQUETS = [
    {
        "id": "portugais-a1-bases",
        "nom": "Portugais A1 — Bases",
        "langue": "pt",
        "description": "Saluer, se presenter, remercier, compter.",
        "niveau": "A1",
        "cartes": [
            # Salutations
            ("Olá", "Bonjour / Salut"),
            ("Bom dia", "Bonjour (le matin)"),
            ("Boa tarde", "Bonjour (l'après-midi)"),
            ("Boa noite", "Bonsoir / Bonne nuit"),
            ("Adeus", "Au revoir"),
            ("Até logo", "À bientôt"),
            ("Até amanhã", "À demain"),
            ("Tudo bem ?", "Ça va ?"),
            ("Tudo bem", "Ça va bien"),
            ("Como está ?", "Comment allez-vous ?"),
            # Politesse
            ("Obrigado", "Merci (dit par un homme)"),
            ("Obrigada", "Merci (dit par une femme)"),
            ("De nada", "De rien"),
            ("Por favor", "S'il vous plaît"),
            ("Desculpe", "Excusez-moi / Pardon"),
            ("Com licença", "Pardon (pour passer)"),
            ("Sim", "Oui"),
            ("Não", "Non"),
            ("Talvez", "Peut-être"),
            ("Se faz favor", "S'il vous plaît (Portugal)"),
            # Se presenter
            ("Como se chama ?", "Comment vous appelez-vous ?"),
            ("Chamo-me Ana", "Je m'appelle Ana"),
            ("Muito prazer", "Enchanté"),
            ("Eu sou francês", "Je suis français"),
            ("Eu sou francesa", "Je suis française"),
            ("De onde é ?", "D'où venez-vous ?"),
            ("Sou de França", "Je viens de France"),
            ("Quantos anos tem ?", "Quel âge avez-vous ?"),
            ("Tenho trinta anos", "J'ai trente ans"),
            ("Falo um pouco de português", "Je parle un peu portugais"),
            ("Não percebo", "Je ne comprends pas"),
            ("Pode repetir ?", "Pouvez-vous répéter ?"),
            ("Fala francês ?", "Parlez-vous français ?"),
            ("Como se diz … ?", "Comment dit-on … ?"),
            ("O que significa ?", "Qu'est-ce que ça veut dire ?"),
            # Nombres
            ("um", "un"),
            ("dois", "deux"),
            ("três", "trois"),
            ("quatro", "quatre"),
            ("cinco", "cinq"),
            ("seis", "six"),
            ("sete", "sept"),
            ("oito", "huit"),
            ("nove", "neuf"),
            ("dez", "dix"),
            ("onze", "onze"),
            ("doze", "douze"),
            ("vinte", "vingt"),
            ("trinta", "trente"),
            ("cem", "cent"),
            ("mil", "mille"),
            # Jours et temps
            ("segunda-feira", "lundi"),
            ("terça-feira", "mardi"),
            ("quarta-feira", "mercredi"),
            ("quinta-feira", "jeudi"),
            ("sexta-feira", "vendredi"),
            ("sábado", "samedi"),
            ("domingo", "dimanche"),
            ("hoje", "aujourd'hui"),
            ("amanhã", "demain"),
            ("ontem", "hier"),
            ("agora", "maintenant"),
            ("sempre", "toujours"),
            ("nunca", "jamais"),
            ("às vezes", "parfois"),
            ("cedo", "tôt"),
            ("tarde", "tard"),
            # Verbes essentiels
            ("ser", "être (permanent)"),
            ("estar", "être (état, lieu)"),
            ("ter", "avoir"),
            ("ir", "aller"),
            ("fazer", "faire"),
            ("querer", "vouloir"),
            ("poder", "pouvoir"),
            ("saber", "savoir"),
            ("falar", "parler"),
            ("comer", "manger"),
            ("beber", "boire"),
            ("dormir", "dormir"),
            ("viver", "vivre"),
            ("ver", "voir"),
            ("ouvir", "entendre"),
            ("gostar", "aimer / apprécier"),
            # Le piege classique
            ("Eu sou professor", "Je suis professeur (métier, durable)"),
            ("Eu estou cansado", "Je suis fatigué (état passager)"),
            ("Ela é alta", "Elle est grande (caractéristique)"),
            ("Ela está em casa", "Elle est à la maison (lieu)"),
        ],
    },
    {
        "id": "portugais-a1-quotidien",
        "nom": "Portugais A1 — Vie quotidienne",
        "langue": "pt",
        "description": "Maison, famille, nourriture, ville, achats.",
        "niveau": "A1",
        "cartes": [
            # Maison
            ("a casa", "la maison"),
            ("o apartamento", "l'appartement"),
            ("a porta", "la porte"),
            ("a janela", "la fenêtre"),
            ("a cozinha", "la cuisine"),
            ("o quarto", "la chambre"),
            ("a casa de banho", "la salle de bain (Portugal)"),
            ("a sala", "le salon"),
            ("a mesa", "la table"),
            ("a cadeira", "la chaise"),
            ("a cama", "le lit"),
            ("a chave", "la clé"),
            ("a luz", "la lumière"),
            ("a água", "l'eau"),
            # Famille
            ("a família", "la famille"),
            ("o pai", "le père"),
            ("a mãe", "la mère"),
            ("o filho", "le fils"),
            ("a filha", "la fille"),
            ("o irmão", "le frère"),
            ("a irmã", "la sœur"),
            ("o avô", "le grand-père"),
            ("a avó", "la grand-mère"),
            ("o marido", "le mari"),
            ("a mulher", "la femme / l'épouse"),
            ("o amigo", "l'ami"),
            ("a amiga", "l'amie"),
            ("o menino", "le garçon"),
            ("a menina", "la fille (enfant)"),
            # Nourriture
            ("o pão", "le pain"),
            ("o leite", "le lait"),
            ("o café", "le café"),
            ("o chá", "le thé"),
            ("o queijo", "le fromage"),
            ("a carne", "la viande"),
            ("o peixe", "le poisson"),
            ("o arroz", "le riz"),
            ("a batata", "la pomme de terre"),
            ("a maçã", "la pomme"),
            ("a laranja", "l'orange"),
            ("o ovo", "l'œuf"),
            ("o açúcar", "le sucre"),
            ("o sal", "le sel"),
            ("o vinho", "le vin"),
            ("a cerveja", "la bière"),
            ("o pequeno-almoço", "le petit-déjeuner (Portugal)"),
            ("o almoço", "le déjeuner"),
            ("o jantar", "le dîner"),
            # Ville
            ("a cidade", "la ville"),
            ("a rua", "la rue"),
            ("a praça", "la place"),
            ("a loja", "le magasin"),
            ("o mercado", "le marché"),
            ("a farmácia", "la pharmacie"),
            ("o hospital", "l'hôpital"),
            ("a estação", "la gare"),
            ("o aeroporto", "l'aéroport"),
            ("a praia", "la plage"),
            ("o restaurante", "le restaurant"),
            ("o hotel", "l'hôtel"),
            ("o banco", "la banque"),
            ("os correios", "la poste"),
            # Transports
            ("o comboio", "le train (Portugal)"),
            ("o autocarro", "le bus (Portugal)"),
            ("o carro", "la voiture"),
            ("o avião", "l'avion"),
            ("a bicicleta", "le vélo"),
            ("o metro", "le métro"),
            ("a pé", "à pied"),
            # Achats et phrases utiles
            ("Quanto custa ?", "Combien ça coûte ?"),
            ("É caro", "C'est cher"),
            ("É barato", "C'est bon marché"),
            ("Queria um café", "Je voudrais un café"),
            ("A conta, por favor", "L'addition, s'il vous plaît"),
            ("Onde fica … ?", "Où se trouve … ?"),
            ("À esquerda", "À gauche"),
            ("À direita", "À droite"),
            ("Em frente", "Tout droit"),
            ("Estou perdido", "Je suis perdu"),
            ("Preciso de ajuda", "J'ai besoin d'aide"),
            ("Que horas são ?", "Quelle heure est-il ?"),
            ("Está aberto", "C'est ouvert"),
            ("Está fechado", "C'est fermé"),
        ],
    },
]
