"""Contenus techniques : raccourcis et langages.

Ces paquets sont d'une nature differente des langues : ce sont des faits
verifiables, pas des traductions. Un raccourci est juste ou faux, et se
constate en trois secondes dans le logiciel.

Ce qui n'est **pas** ici, et pourquoi
-------------------------------------
Pas de code de la route. Les regles changent, varient d'un pays a l'autre, et
une reponse fausse s'y paie en points de permis ou pire. Produire un paquet
que je ne peux pas verifier contre un texte officiel a jour serait irresponsable
— c'est exactement le genre de contenu qui doit venir d'une source qui engage
sa responsabilite, pas d'une generation.
"""

PAQUETS = [
    {
        "id": "blender-raccourcis",
        "nom": "Blender — Raccourcis",
        "langue": "",
        "description": "Les raccourcis clavier du travail quotidien.",
        "niveau": "",
        "cartes": [
            ("Déplacer un objet", "G"),
            ("Pivoter un objet", "R"),
            ("Redimensionner", "S"),
            ("Contraindre à l'axe X", "G puis X"),
            ("Dupliquer", "Maj + D"),
            ("Dupliquer en lien (instance)", "Alt + D"),
            ("Supprimer", "X"),
            ("Annuler", "Ctrl + Z"),
            ("Rétablir", "Ctrl + Maj + Z"),
            ("Ajouter un objet", "Maj + A"),
            ("Mode Édition / Objet", "Tab"),
            ("Sélectionner tout", "A"),
            ("Tout désélectionner", "Alt + A"),
            ("Inverser la sélection", "Ctrl + I"),
            ("Vue caméra", "Pavé num. 0"),
            ("Vue de face", "Pavé num. 1"),
            ("Vue de côté", "Pavé num. 3"),
            ("Vue de dessus", "Pavé num. 7"),
            ("Basculer perspective / ortho", "Pavé num. 5"),
            ("Cadrer sur la sélection", "Pavé num. ."),
            ("Rendu image", "F12"),
            ("Menu de recherche", "F3"),
            ("Extruder", "E"),
            ("Biseauter (bevel)", "Ctrl + B"),
            ("Coupe en boucle", "Ctrl + R"),
            ("Subdiviser", "Clic droit puis Subdivide"),
            ("Fusionner des sommets", "M"),
            ("Séparer une sélection", "P"),
            ("Joindre des objets", "Ctrl + J"),
            ("Parenter", "Ctrl + P"),
            ("Retirer le parent", "Alt + P"),
            ("Masquer la sélection", "H"),
            ("Réafficher tout", "Alt + H"),
            ("Isoler la sélection", "/"),
            ("Mode sommets / arêtes / faces", "1 / 2 / 3"),
            ("Pivot sur le curseur 3D", "Point + C"),
            ("Placer le curseur 3D", "Maj + clic droit"),
            ("Curseur 3D à l'origine", "Maj + C"),
            ("Appliquer transformations", "Ctrl + A"),
            ("Mode sculpture / pose", "Ctrl + Tab"),
            ("Insérer une image clé", "I"),
            ("Lecture de l'animation", "Espace"),
            ("Ombrage rendu / solide", "Z"),
            ("Proportional editing", "O"),
            ("Snap (aimantation)", "Maj + Tab"),
        ],
    },
    {
        "id": "vscode-raccourcis",
        "nom": "VS Code — Raccourcis",
        "langue": "",
        "description": "Les raccourcis Windows et Linux qui font gagner du temps.",
        "niveau": "",
        "cartes": [
            ("Palette de commandes", "Ctrl + Maj + P"),
            ("Ouvrir un fichier par son nom", "Ctrl + P"),
            ("Rechercher dans le fichier", "Ctrl + F"),
            ("Rechercher dans le projet", "Ctrl + Maj + F"),
            ("Remplacer", "Ctrl + H"),
            ("Aller à la ligne", "Ctrl + G"),
            ("Aller à la définition", "F12"),
            ("Aperçu de la définition", "Alt + F12"),
            ("Retour arrière (navigation)", "Alt + ←"),
            ("Renommer le symbole", "F2"),
            ("Commenter la ligne", "Ctrl + /"),
            ("Commenter un bloc", "Maj + Alt + A"),
            ("Dupliquer la ligne", "Maj + Alt + ↓"),
            ("Déplacer la ligne", "Alt + ↑ / ↓"),
            ("Supprimer la ligne", "Ctrl + Maj + K"),
            ("Curseur multiple", "Alt + clic"),
            ("Sélectionner l'occurrence suivante", "Ctrl + D"),
            ("Sélectionner toutes les occurrences", "Ctrl + Maj + L"),
            ("Formater le document", "Maj + Alt + F"),
            ("Replier / déplier", "Ctrl + Maj + [ / ]"),
            ("Terminal intégré", "Ctrl + ù"),
            ("Nouveau terminal", "Ctrl + Maj + ù"),
            ("Explorateur de fichiers", "Ctrl + Maj + E"),
            ("Contrôle de source", "Ctrl + Maj + G"),
            ("Extensions", "Ctrl + Maj + X"),
            ("Fermer l'onglet", "Ctrl + W"),
            ("Rouvrir l'onglet fermé", "Ctrl + Maj + T"),
            ("Diviser l'éditeur", "Ctrl + \\"),
            ("Zen mode", "Ctrl + K puis Z"),
            ("Réglages", "Ctrl + ,"),
        ],
    },
    {
        "id": "kotlin-bases",
        "nom": "Kotlin — Bases",
        "langue": "",
        "description": "Syntaxe et idiomes courants du langage.",
        "niveau": "",
        "cartes": [
            ("Déclarer une variable immuable", "val x = 1"),
            ("Déclarer une variable modifiable", "var x = 1"),
            ("Type explicite", "val x: Int = 1"),
            ("Type nullable", "val x: String? = null"),
            ("Appel sûr sur un nullable", "x?.length"),
            ("Valeur de repli si null", "x ?: \"defaut\""),
            ("Lever si null", "x!!"),
            ("Interpolation dans une chaîne", "\"Bonjour $nom\""),
            ("Expression dans une chaîne", "\"Total : ${a + b}\""),
            ("Fonction courte", "fun double(x: Int) = x * 2"),
            ("Paramètre par défaut", "fun f(n: Int = 0)"),
            ("Argument nommé", "f(n = 3)"),
            ("Classe de données", "data class P(val x: Int)"),
            ("Copie modifiée", "p.copy(x = 2)"),
            ("Singleton", "object Config"),
            ("Compagnon (statique)", "companion object { }"),
            ("Énumération", "enum class Etat { OK, KO }"),
            ("Hiérarchie fermée", "sealed interface Resultat"),
            ("Condition comme expression", "val s = if (a) 1 else 2"),
            ("Aiguillage exhaustif", "when (x) { ... }"),
            ("Boucle sur un intervalle", "for (i in 0 until n)"),
            ("Intervalle inclusif", "for (i in 0..n)"),
            ("Parcourir une liste", "for (e in liste)"),
            ("Transformer une liste", "liste.map { it * 2 }"),
            ("Filtrer une liste", "liste.filter { it > 0 }"),
            ("Premier élément ou null", "liste.firstOrNull()"),
            ("Somme", "liste.sumOf { it.prix }"),
            ("Grouper", "liste.groupBy { it.type }"),
            ("Trier", "liste.sortedBy { it.nom }"),
            ("Exécuter sur un objet non nul", "x?.let { ... }"),
            ("Configurer puis rendre l'objet", "obj.apply { ... }"),
            ("Rendre un autre résultat", "obj.run { ... }"),
            ("Fonction d'extension", "fun String.crier() = uppercase()"),
            ("Interface fonctionnelle", "fun interface Clic"),
            ("Fonction suspendue", "suspend fun charger()"),
            ("Lancer une coroutine", "scope.launch { ... }"),
            ("Attendre un résultat", "val r = async { ... }.await()"),
            ("Changer de fil d'exécution", "withContext(Dispatchers.IO) { }"),
            ("Flux de valeurs", "flow { emit(1) }"),
            ("État observable", "MutableStateFlow(0)"),
            ("Capturer une exception", "runCatching { ... }"),
            ("Délégation par paresse", "val x by lazy { ... }"),
            ("Destructuration", "val (a, b) = paire"),
            ("Créer une liste", "listOf(1, 2, 3)"),
            ("Créer une liste modifiable", "mutableListOf<Int>()"),
            ("Créer une table", "mapOf(\"a\" to 1)"),
        ],
    },
]
